;;; emacs-smoke.el --- Offline full-init smoke check -*- lexical-binding: t; -*-
;; Uses installed packages but a temporary HOME, state directory and Custom.
;; Does not open project files or start language servers.
(require 'cl-lib)
(require 'package)
(let* ((repo (expand-file-name "../.." (file-name-directory load-file-name)))
       (source (expand-file-name "emacs/.emacs.d/" repo))
       (home (make-temp-file "tilde-emacs-smoke-" t))
       (user-emacs-directory (expand-file-name ".emacs.d/" home))
       (package-user-dir (expand-file-name "elpa" source))
       (process-environment (copy-sequence process-environment)))
  (unwind-protect
      (progn
        (setenv "HOME" home)
        (make-directory user-emacs-directory t)
        (dolist (name '("modules" "themes" "scripts.el"))
          (make-symbolic-link (expand-file-name name source)
                              (expand-file-name name user-emacs-directory)))
        (when (and (fboundp 'startup-redirect-eln-cache)
                   (boundp 'native-comp-eln-load-path))
          (startup-redirect-eln-cache (expand-file-name "eln-cache/" home)))
        (cl-letf (((symbol-function 'package-refresh-contents)
                   (lambda (&rest _) (error "Unexpected package refresh")))
                  ((symbol-function 'package-install)
                   (lambda (&rest _) (error "Unexpected package install")))
                  ((symbol-function 'url-retrieve)
                   (lambda (&rest _) (error "Unexpected network request")))
                  ((symbol-function 'url-retrieve-synchronously)
                   (lambda (&rest _) (error "Unexpected network request"))))
          (load (expand-file-name "init.el" source) nil t t))
        (unless (eq lsp-completion-provider :capf)
          (error "Completion provider changed"))
        (unless (equal custom-file (expand-file-name "custom.el" user-emacs-directory))
          (error "Custom escaped temporary state directory"))
        (princ "PASS: full init loads offline with installed packages and isolated state\n"))
    ;; Shut down modes that install `kill-emacs-hook' writers so the
    ;; temp HOME can vanish without a save-time warning at exit.
    (when (bound-and-true-p savehist-mode) (savehist-mode -1))
    (when (bound-and-true-p recentf-mode) (recentf-mode -1))
    (when (bound-and-true-p global-auto-revert-mode)
      (global-auto-revert-mode -1))
    (delete-directory home t)))
